FROM arm32v6/alpine
MAINTAINER Daniel Randall <danny_randall@byu.edu>

ARG NAME
ENV name=${NAME}

COPY ${name}-arm ${name}-arm 

# add any required files/folders
COPY blueberry-dist blueberry-dist

ENTRYPOINT ./${name}-arm
EXPOSE 8888
