FROM resin/armv7hf-debian-qemu

RUN [ "cross-build-start" ]

RUN apt-get update && \
    # apt-get -y upgrade && \
    # apt-get -y install curl && \
    apt-get -y install golang && \
    # curl -O https://storage.googleapis.com/golang/go1.6.3.linux-armv6l.tar.gz && \
    # tar -xvf go1.6.3.linux-armv6l.tar.gz && \
    # mv go /usr/local && \
    export PATH=$PATH:/usr/local/go/bin

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/raspi-tp

WORKDIR /go/src/github.com/byuoitav/raspi-tp
RUN go get -d -v && \
    go install -v

CMD ["/go/bin/raspi-tp"]

RUN [ "cross-build-end" ]
